apiVersion: v1
kind: Service
metadata:
  name: openpitrix-hyperpitrix
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-hyperpitrix
    version: ${VERSION}
spec:
  selector:
    app: openpitrix
    component: openpitrix-hyperpitrix
  ports:
  - name: openpitrix-api-manager
    protocol: TCP
    port: 9100
    targetPort: 9100
  - name: openpitrix-app-manager
    protocol: TCP
    port: 9102
    targetPort: 9102
  - name: openpitrix-category-manager
    protocol: TCP
    port: 9113
    targetPort: 9113
  - name: openpitrix-attachment-manager
    protocol: TCP
    port: 9120
    targetPort: 9120
  - name: openpitrix-cluster-manager
    protocol: TCP
    port: 9104
    targetPort: 9104
  - name: openpitrix-isv-manager
    protocol: TCP
    port: 9118
    targetPort: 9118
  - name: openpitrix-job-manager
    protocol: TCP
    port: 9106
    targetPort: 9106
  - name: openpitrix-repo-manager
    protocol: TCP
    port: 9101
    targetPort: 9101
  - name: openpitrix-repo-indexer
    protocol: TCP
    port: 9108
    targetPort: 9108
  - name: openpitrix-rp-manager
    protocol: TCP
    port: 9121
    targetPort: 9121
  - name: openpitrix-runtime-manager
    protocol: TCP
    port: 9103
    targetPort: 9103
  - name: openpitrix-task-manager
    protocol: TCP
    port: 9107
    targetPort: 9107

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-hyperpitrix-deployment
  namespace: ${NAMESPACE}
  labels:
    app: openpitrix
    component: openpitrix-hyperpitrix
    version: ${VERSION}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-hyperpitrix
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-hyperpitrix
        version: ${VERSION}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-db.${NAMESPACE}.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z openpitrix-etcd.${NAMESPACE}.svc 2379; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-api-gateway
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
        - api-gateway
        ports:
        - containerPort: 9100
          name: api-gateway
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: "${GRPC_SHOW_ERROR_CAUSE}"
        - name: OPENPITRIX_LOG_LEVEL
          value: ${OPENPITRIX_LOG_LEVEL}
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-app-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - app-manager
        ports:
          - containerPort: 9102
            name: app-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "app"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-category-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - category-manager
        ports:
          - containerPort: 9108
            name: cateogory-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "app"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-attachment-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - attachment-manager
        ports:
          - containerPort: 9120
            name: attachment-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "attachment"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-cluster-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - cluster-manager
        ports:
          - containerPort: 9104
            name: cluster-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "cluster"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-isv-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - isv-manager
        ports:
          - containerPort: 9118
            name: isv-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "isv"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-job-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - job-manager
        ports:
          - containerPort: 9106
            name: job-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "job"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-repo-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - repo-manager
        ports:
          - containerPort: 9101
            name: repo-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "repo"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-repo-indexer
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - repo-indexer
        ports:
          - containerPort: 9108
            name: repo-indexer
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "repo"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-rp-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - runtime-provider-manager
        ports:
          - containerPort: 9121
            name: rp-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-runtime-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - runtime-manager
        ports:
          - containerPort: 9103
            name: runtime-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "runtime"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi
      - name: openpitrix-task-manager
        image: ${IMAGE}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        command:
          - task-manager
        ports:
          - containerPort: 9107
            name: task-mgr
        env:
          - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
            value: "${GRPC_SHOW_ERROR_CAUSE}"
          - name: OPENPITRIX_LOG_LEVEL
            value: ${OPENPITRIX_LOG_LEVEL}
          - name: OPENPITRIX_MYSQL_DATABASE
            value: "task"
          - name: OPENPITRIX_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password.txt
                name: mysql-pass
        resources:
          limits:
            cpu: ${CPU_LIMITS}m
            memory: ${MEMORY_LIMITS}Mi
          requests:
            cpu: ${CPU_REQUESTS}m
            memory: ${MEMORY_REQUESTS}Mi

